GET http://localhost:3000/applications/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJociIsImlhdCI6MTc2ODI4NzgyNiwiZXhwIjoxNzY4Mjk1MDI2fQ.pHR9zdYZ2FK7bUSyaTFj6KSVaq2QHWUBBbODnkKW1Fc
Content-Type: application/json

{}
###



GET http://localhost:3000/applications/1118153007301165057
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTE4MTUyMDIzMTA4NTUwNjU3Iiwicm9sZSI6ImhyIiwiaWF0IjoxNzYxMzA5OTY3LCJleHAiOjE3NjEzMTcxNjd9.cZhIqpGsYaXO-vuJOADnPgtzUSCtdwS7CERpMUbHgjU
Content-Type: application/json

{}
