GET http://localhost:3000/job/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTE4MTUyMDIzMTA4NTUwNjU3Iiwicm9sZSI6ImhyIiwiaWF0IjoxNzYxMzEyMDUyLCJleHAiOjE3NjEzMTkyNTJ9.LYWRhGgk1y8-n68G208MVxwkkVMIzWtQEugYrXLTDtA
Content-Type: application/json

{}
